const countryList = {
  AED: "United Arab Emirates",
  AFN: "Afghanistan",
  // XCD: "East Caribbean Dollar",
  ALL: "Albania",
  AMD: "Armenia",
  ANG: "Netherlands Antillean Guilder",
  AOA: "Angola",
  AQD: "Antarctica",
  ARS: "Argentina",
  AUD: "Australia",
  AZN: "Azerbaijan",
  BAM: "Bosnia and Herzegovina",
  BBD: "Barbados",
  BDT: "Bangladesh",
  XOF: "West African CFA franc",
  BGN: "Bulgaria",
  BHD: "Bahrain",
  BIF: "Burundi",
  BMD: "Bermuda",
  BND: "Brunei",
  BOB: "Bolivia",
  BRL: "Brazil",
  BSD: "Bahamas",
  NOK: "Norway",
  BWP: "Botswana",
  BYR: "Belarus",
  BZD: "Belize",
  CAD: "Canadq",
  CDF: "Democratic Republic of the Congo",
  XAF: "Central African Republic",
  CHF: "Switzerland",
  CLP: "Chile",
  CNY: "China",
  COP: "Colombia",
  CRC: "Costa Rica",
  CUP: "Cuba",
  CVE: "Cape Verde",
  CYP: "Cyprus ",
  CZK: "Czech Republic",
  DJF: "Djibouti",
  DKK: "Denmark",
  DOP: "Dominica",
  DZD: "Algeria",
  ECS: "Ecuador",
  EEK: "Estonia",
  EGP: "Egypt",
  ETB: "Eritrea",
  EUR: "France",
  FJD: "Fiji",
  FKP: "Falkland Islands",
  GBP: "United Kingdom",
  GEL: "Georgia",
  GGP: "Guernsey",
  GHS: "Ghana",
  GIP: "Gibraltar",
  GMD: "Gambia",
  GNF: "Guinea",
  GTQ: "Guatemala",
  GYD: "Guyana",
  HKD: "Hong Kong",
  HNL: "Honduras",
  HRK: "Croatia",
  HTG: "Haiti",
  HUF: "Hungary",
  IDR: "Indonesia",
  ILS: "Israel",
  INR: "India",
  IQD: "Iraq",
  IRR: "Iran",
  ISK: "Iceland",
  JMD: "Jamaica",
  JOD: "Jordan",
  JPY: "Japan",
  KES: "Kenya",
  KGS: "Kyrgyzstan",
  KHR: "Cambodia",
  KMF: "Comoros",
  KPW: "North Korea",
  KRW: "South Korea",
  KWD: "Kuwait",
  KYD: "Cayman Islands",
  KZT: "Kazakhstan",
  LAK: "Laos",
  LBP: "Lebanon",
  LKR: "Sri Lanka",
  LRD: "Liberia",
  LSL: "Lesotho",
  LTL: "Lithuania",
  LVL: "Latvia",
  LYD: "Libya",
  MAD: "Morocco",
  MDL: "Moldova",
  MGA: "Madagascar",
  MKD: "Macedonia",
  MMK: "Myanmar",
  MNT: "Mongolia",
  MOP: "Macau",
  MRO: "Mauritania",
  MTL: "Malta",
  MUR: "Mauritius",
  MVR: "Maldives",
  MWK: "Malawi",
  MXN: "Mexico",
  MYR: "Malaysia",
  MZN: "Mozambique",
  NAD: "Namibia",
  XPF: "New Caledonia",
  NGN: "Nigeria",
  NIO: "Nicaragua",
  NPR: "Nepal",
  NZD: "New Zealand",
  OMR: "Oman",
  PAB: "Panama",
  // PEN: "Peru",
  PHP: "Philippines",
  PKR: "Pakistan",
  PLN: "Poland",
  PYG: "Paraguay",
  QAR: "Qatar",
  RON: "Romania",
  RSD: "Serbia",
  RUB: "Russia",
  RWF: "Rwanda",
  SAR: "Saudi Arabia",
  SBD: "Solomon Islands",
  SCR: "Seychelles",
  SDG: "Sudan",
  SEK: "Sweden",
  SGD: "Singapore",
  SKK: "Slovakia",
  SLL: "Sierra Leone",
  SOS: "Somalia",
  SRD: "Suriname",
  STD: "São Tomé and Príncipe",
  SVC: "El Salvador",
  SYP: "Syria",
  SZL: "Eswatini",
  THB: "Thailand",
  TJS: "Tajikistan",
  TMT: "Turkmenistan",
  TND: "Tunisia",
  TOP: "Tonga",
  TRY: "Turkey",
  TTD: "Trinidad and Tobago",
  TWD: "Taiwan",
  TZS: "Tanzania",
  UAH: "Ukraine",
  UGX: "Uganda",
  USD: "United States",
  UYU: "Uruguay",
  UZS: "Uzbekistan",
  VEF: "Venezuela",
  VND: "Vietnam",
  VUV: "Vanuatu",
  YER: "Yemen",
  ZAR: "South Africa",
  ZMK: "Zambia",
  ZWD: "Zimbabwe"
  };

  const countryFlag = {
    "United Arab Emirates": "AE",
    "Afghanistan": "AF",
    // "Antigua and Barbuda": "AG",
    "Albania": "AL",
    "Armenia": "AM",
    "Netherlands Antillean Guilder": "AN",
    "Angola": "AO",
    "Antarctica": "AQ",
    "Argentina": "AR",
    "Australia": "AU",
    "Azerbaijan": "AZ",
    "Bosnia and Herzegovina": "BA",
    "Barbados": "BB",
    "Bangladesh": "BD",
    "West African CFA franc":"BE",
    "Belgium": "BE",
    "Bulgaria": "BG",
    "Bahrain": "BH",
    "Burundi": "BI",
    "Bermuda": "BM",
    "Brunei": "BN",
    "Bolivia": "BO",
    "Brazil": "BR",
    "Bahamas": "BS",
    "Norway":"NR",
    "Bouvet Island": "BV",
    "Botswana": "BW",
    "Belarus": "BY",
    "Belize": "BZ",
    "Canada": "CA",
    "Democratic Republic of the Congo": "CD",
    "Central African Republic": "CF",
    "Switzerland": "CH",
    "Chile": "CL",
    "China": "CN",
    "Colombia": "CO",
    "Costa Rica": "CR",
    "Cuba": "CU",
    "Cape Verde": "CV",
    "Cyprus": "CY",
    "Czech Republic": "CZ",
    "Djibouti": "DJ",
    "Denmark": "DK",
    "Dominica": "DO",
    "Algeria": "DZ",
    "Ecuador": "EC",
    "Estonia": "EE",
    "Egypt": "EG",
    "Eritrea": "ET",
    "France": "FR",
    "Fiji": "FJ",
    "Falkland Islands": "FK",
    "United Kingdom": "GB",
    "Georgia": "GE",
    "Guernsey": "GG",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Gambia": "GM",
    "Guinea": "GN",
    "Guatemala": "GT",
    "Guyana": "GY",
    "Hong Kong": "HK",
    "Honduras": "HN",
    "Croatia": "HR",
    "Haiti": "HT",
    "Hungary": "HU",
    "Indonesia": "ID",
    "Israel": "IL",
    "India": "IN",
    "Iraq": "IQ",
    "Iran": "IR",
    "Iceland": "IS",
    "Jamaica": "JM",
    "Jordan": "JO",
    "Japan": "JP",
    "Kenya": "KE",
    "Kyrgyzstan": "KG",
    "Cambodia": "KH",
    "Comoros": "KM",
    "North Korea": "KP",
    "South Korea": "KR",
    "Kuwait": "KW",
    "Cayman Islands": "KY",
    "Kazakhstan": "KZ",
    "Laos": "LA",
    "Lebanon": "LB",
    "Sri Lanka": "LK",
    "Liberia": "LR",
    "Lesotho": "LS",
    "Lithuania": "LT",
    "Latvia": "LV",
    "Libya": "LY",
    "Morocco": "MA",
    "Moldova": "MD",
    "Madagascar": "MG",
    "Macedonia": "MK",
    "Myanmar": "MM",
    "Mongolia": "MN",
    "Macau": "MO",
    "Mauritania": "MR",
    "Malta": "MT",
    "Mauritius": "MU",
    "Maldives": "MV",
    "Malawi": "MW",
    "Mexico": "MX",
    "Malaysia": "MY",
    "Mozambique": "MZ",
    "Namibia": "NA",
    "New Caledonia": "NC",
    "Nigeria": "NG",
    "Nicaragua": "NI",
    "Nepal": "NP",
    "New Zealand": "NZ",
    "Oman": "OM",
    "Panama": "PA",
    "Peru": "PE",
    "Papua New Guinea": "PG",
    "Philippines": "PH",
    "Pakistan": "PK",
    "Poland": "PL",
    "Paraguay": "PY",
    "Qatar": "QA",
    "Romania": "RO",
    "Serbia": "RS",
    "Russia": "RU",
    "Rwanda": "RW",
    "Saudi Arabia": "SA",
    "Solomon Islands": "SB",
    "Seychelles": "SC",
    "Sudan": "SD",
    "Sweden": "SE",
    "Singapore": "SG",
    "Slovakia": "SK",
    "Sierra Leone": "SL",
    "Somalia": "SO",
    "Suriname": "SR",
    "São Tomé and Príncipe": "ST",
    "El Salvador": "SV",
    "Syria": "SY",
    "Eswatini": "SZ",
    "Thailand": "TH",
    "Tajikistan": "TJ",
    "Turkmenistan": "TM",
    "Tunisia": "TN",
    "Tonga": "TO",
    "Turkey": "TR",
    "Trinidad and Tobago": "TT",
    "Taiwan": "TW",
    "Tanzania": "TZ",
    "Ukraine": "UA",
    "Uganda": "UG",
    "United States": "US",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Venezuela": "VE",
    "Vietnam": "VN",
    "Vanuatu": "VU",
    "Yemen": "YE",
    "South Africa": "ZA",
    "Zambia": "ZM",
    "Zimbabwe": "ZW"
};

