const countryFlag = {
    "United Arab Emirates": "AE",
    "Afghanistan": "AF",
    // "Antigua and Barbuda": "AG",
    "Albania": "AL",
    "Armenia": "AM",
    "Netherlands Antillean Guilder": "AN",
    "Angola": "AO",
    "Antarctica": "AQ",
    "Argentina": "AR",
    "Australia": "AU",
    "Azerbaijan": "AZ",
    "Bosnia and Herzegovina": "BA",
    "Barbados": "BB",
    "Bangladesh": "BD",
    "West African CFA franc":"BE",
    "Belgium": "BE",
    "Bulgaria": "BG",
    "Bahrain": "BH",
    "Burundi": "BI",
    "Bermuda": "BM",
    "Brunei": "BN",
    "Bolivia": "BO",
    "Brazil": "BR",
    "Bahamas": "BS",
    "Norway":"NR",
    "Bouvet Island": "BV",
    "Botswana": "BW",
    "Belarus": "BY",
    "Belize": "BZ",
    "Canada": "CA",
    "Democratic Republic of the Congo": "CD",
    "Central African Republic": "CF",
    "Switzerland": "CH",
    "Chile": "CL",
    "China": "CN",
    "Colombia": "CO",
    "Costa Rica": "CR",
    "Cuba": "CU",
    "Cape Verde": "CV",
    "Cyprus": "CY",
    "Czech Republic": "CZ",
    "Djibouti": "DJ",
    "Denmark": "DK",
    "Dominica": "DO",
    "Algeria": "DZ",
    "Ecuador": "EC",
    "Estonia": "EE",
    "Egypt": "EG",
    "Eritrea": "ET",
    "France": "FR",
    "Fiji": "FJ",
    "Falkland Islands": "FK",
    "United Kingdom": "GB",
    "Georgia": "GE",
    "Guernsey": "GG",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Gambia": "GM",
    "Guinea": "GN",
    "Guatemala": "GT",
    "Guyana": "GY",
    "Hong Kong": "HK",
    "Honduras": "HN",
    "Croatia": "HR",
    "Haiti": "HT",
    "Hungary": "HU",
    "Indonesia": "ID",
    "Israel": "IL",
    "India": "IN",
    "Iraq": "IQ",
    "Iran": "IR",
    "Iceland": "IS",
    "Jamaica": "JM",
    "Jordan": "JO",
    "Japan": "JP",
    "Kenya": "KE",
    "Kyrgyzstan": "KG",
    "Cambodia": "KH",
    "Comoros": "KM",
    "North Korea": "KP",
    "South Korea": "KR",
    "Kuwait": "KW",
    "Cayman Islands": "KY",
    "Kazakhstan": "KZ",
    "Laos": "LA",
    "Lebanon": "LB",
    "Sri Lanka": "LK",
    "Liberia": "LR",
    "Lesotho": "LS",
    "Lithuania": "LT",
    "Latvia": "LV",
    "Libya": "LY",
    "Morocco": "MA",
    "Moldova": "MD",
    "Madagascar": "MG",
    "Macedonia": "MK",
    "Myanmar": "MM",
    "Mongolia": "MN",
    "Macau": "MO",
    "Mauritania": "MR",
    "Malta": "MT",
    "Mauritius": "MU",
    "Maldives": "MV",
    "Malawi": "MW",
    "Mexico": "MX",
    "Malaysia": "MY",
    "Mozambique": "MZ",
    "Namibia": "NA",
    "New Caledonia": "NC",
    "Nigeria": "NG",
    "Nicaragua": "NI",
    "Nepal": "NP",
    "New Zealand": "NZ",
    "Oman": "OM",
    "Panama": "PA",
    "Peru": "PE",
    "Papua New Guinea": "PG",
    "Philippines": "PH",
    "Pakistan": "PK",
    "Poland": "PL",
    "Paraguay": "PY",
    "Qatar": "QA",
    "Romania": "RO",
    "Serbia": "RS",
    "Russia": "RU",
    "Rwanda": "RW",
    "Saudi Arabia": "SA",
    "Solomon Islands": "SB",
    "Seychelles": "SC",
    "Sudan": "SD",
    "Sweden": "SE",
    "Singapore": "SG",
    "Slovakia": "SK",
    "Sierra Leone": "SL",
    "Somalia": "SO",
    "Suriname": "SR",
    "São Tomé and Príncipe": "ST",
    "El Salvador": "SV",
    "Syria": "SY",
    "Eswatini": "SZ",
    "Thailand": "TH",
    "Tajikistan": "TJ",
    "Turkmenistan": "TM",
    "Tunisia": "TN",
    "Tonga": "TO",
    "Turkey": "TR",
    "Trinidad and Tobago": "TT",
    "Taiwan": "TW",
    "Tanzania": "TZ",
    "Ukraine": "UA",
    "Uganda": "UG",
    "United States": "US",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Venezuela": "VE",
    "Vietnam": "VN",
    "Vanuatu": "VU",
    "Yemen": "YE",
    "South Africa": "ZA",
    "Zambia": "ZM",
    "Zimbabwe": "ZW"
};
